create table if not exists `cdr`
(
    `id` int primary key auto_increment,
    `call_date` varchar(50) not null,
    `clid` varchar(150) not null,
    `src` varchar(50) not null,
    `dst` varchar(50) not null,
    `dcontext` varchar(50) not null,
    `channel` varchar(50) not null,
    `dstchannel` varchar(150) not null,
    `lastapp` varchar(50) not null,
    `lastdata` varchar(150) null,
    `duration` varchar(50) not null,
    `billsec` varchar(50) not null,
    `disposition` varchar(50) not null,
    `amaflags` varchar(50) not null,
    `accountcode` varchar(50) null,
    `uniqueid` varchar(150) not null,
    `userfield` varchar(50) null,
    `did` varchar(50) null,
    `recordingfile` varchar(150) null,
    `cnum` varchar(50) not null,
    `cnam` varchar(50) not null,
    `outbound_cnum` varchar(50) null,
    `outbound_cnam` varchar(50) null,
    `dst_cnam` varchar(50) not null,
    `linkedid` varchar(50) not null,
    `peeraccount` varchar(50) null,
    `sequence` varchar(50) not null,
    `created_date` datetime(3) not null
)charset=utf8mb4;